### ISSUE TITLE
Text and images in Introduction change size

### ISSUE THREAD

**Issue by harveykliman** [estimated-placental-volume/EPVRK#14]
When viewing the Introduction pages, the text and pictures momentarily adjust their size, giving the user a sense of the page being unstable. It almost looks like a font size issue as the text slightly changes after opening a page.

**Comment by fastharper** [comment]
I was able to reproduce this in the 8.4 Simulator, but not the 9.0 Simulator. It also occurs on my iPhone 5S which has iOS 8.4.1. It does not happen on my iPhone 6+ with iOS 9

So I think this is an 8.4.x issue.

The problem is in the underlying UIPageViewController I'm using - the thing which has the left-right swiping. To fix the issue I would have to write my own. Would take a day. Don't think it's worth it.

**Comment by harveykliman** [comment]
Agreed. Suggest we close this issue then. Or we ask Apple folks about it this Wednesday.

**Comment by harveykliman** [comment]
This now is fixed in iOS 9.0.1

**Comment by harveykliman** [comment]
This now is fixed in iOS 9.0.1
